import { getKhaiVanSkill, type KhaiVanSkill } from "../data/khai-van-skills";
import { makeReportId, type Report } from "../data/reports";
import { getTemplate, type SkillTemplate } from "../data/skill-templates";
import { buildContext, render } from "./context";

export type SkillFile = {
  path: string;
  content: string;
};

export type BuildResult = {
  folderName: string;
  files: SkillFile[];
};

/**
 * Coach output — given a completed profile for a KhaiVanSkill, produce the
 * human-readable Report the user reviews before Skill Forge runs.
 *
 * Phase 2 renders the report via pure interpolation of `khaiVan.reportTemplate`.
 * Later phases can swap this for an LLM pass (e.g. to tighten prose or synthesize
 * across slots) without changing the caller's contract.
 */
export function renderReport(
  khaiVan: KhaiVanSkill,
  profile: Record<string, unknown>,
  opts?: { userId?: string; version?: number },
): Report {
  const userId = opts?.userId ?? "anonymous";
  const version = opts?.version ?? 1;
  const ctx = buildContext(khaiVan.slots, profile);
  const markdown = render(khaiVan.reportTemplate, ctx);
  const now = new Date().toISOString();
  return {
    id: makeReportId(userId, khaiVan.id, version),
    userId,
    khaiVanSkillId: khaiVan.id,
    version,
    status: "draft",
    createdAt: now,
    updatedAt: now,
    data: profile,
    markdown,
  };
}

/**
 * Skill Forge — given the user's confirmed Report and a SkillTemplate, produce
 * the final personalized skill folder (SKILL.md + README.md + config.json).
 *
 * Phase 2 forges via pure interpolation of `template.skillBody`/`skillDescription`
 * against the Report's data. The intent of an LLM-driven remix (per the product
 * description — unique, non-shareable outputs) is deferred to Phase 2b; plugging
 * it in means replacing the `render(...)` calls below with an LLM provider call
 * that receives `(template, report)` and returns the final body.
 */
export function forgeSkill(
  template: SkillTemplate,
  report: Report,
): BuildResult | null {
  const khaiVan = getKhaiVanSkill(report.khaiVanSkillId);
  if (!khaiVan) return null;

  const ctx = buildContext(khaiVan.slots, report.data);
  const description = render(template.skillDescription, ctx);
  const body = render(template.skillBody, ctx);

  const skillMd = `---
name: ${template.folderName}
description: ${description.replace(/\n/g, " ").trim()}
---

${body}`;

  const readme = `# ${template.skillDisplayName}

This skill was generated by Skillforge for your team. It's a standalone Agent Skill
folder that can be dropped into any compatible agent runtime (for example,
Claude Code's \`~/.claude/skills/\` directory or the Claude Agent SDK).

## Install

1. Unzip this folder to your agent's skills directory.
   For Claude Code: \`~/.claude/skills/${template.folderName}\`
2. Restart your agent (or reload skills).
3. The skill will be loaded automatically when relevant to the task.

## Files

- \`SKILL.md\` — the skill definition consumed by the agent.
- \`config.json\` — the raw configuration captured from your interview, kept
  alongside for traceability. Safe to delete if you don't need the audit trail.
- \`README.md\` — this file.

## Regenerating

If your team's setup changes, open a new private room on Skillforge and
re-run the interview. Your new skill folder will supersede this one.
`;

  const config = JSON.stringify(
    {
      templateId: template.id,
      khaiVanSkillId: khaiVan.id,
      reportId: report.id,
      generatedAt: new Date().toISOString(),
      profile: report.data,
    },
    null,
    2,
  );

  return {
    folderName: template.folderName,
    files: [
      { path: `${template.folderName}/SKILL.md`, content: skillMd },
      { path: `${template.folderName}/README.md`, content: readme },
      { path: `${template.folderName}/config.json`, content: config },
    ],
  };
}

/**
 * Legacy one-shot entry point: `(templateId, profile)` → final skill folder.
 *
 * Retained so `/api/finalize` can keep its current request shape. Internally it
 * now runs the Phase 2 two-step pipeline (renderReport → forgeSkill) so there is
 * a single forge implementation. Callers that need the intermediate Report (UI
 * preview, persistence in later phases) should call `renderReport` and
 * `forgeSkill` directly.
 */
export function buildSkill(
  templateId: string,
  profile: Record<string, unknown>,
): BuildResult | null {
  const template = getTemplate(templateId);
  if (!template) return null;
  const khaiVan = getKhaiVanSkill(template.khaiVanSkillId);
  if (!khaiVan) return null;
  const report = renderReport(khaiVan, profile);
  return forgeSkill(template, report);
}
