import { getSchema, type SkillSchema, type Slot } from "../data/schemas";
import { getTemplate } from "../data/skill-templates";

export type SkillFile = {
  path: string;
  content: string;
};

export type BuildResult = {
  folderName: string;
  files: SkillFile[];
};

const APPROVAL_BLOCKS: Record<string, string> = {
  auto:
    "Act autonomously on routine, low-risk tasks. Summarize what you did at the end of every work session.",
  confirm:
    "Before any action that leaves the team's systems (sending email, writing to a system of record, calling an external API), confirm intent with the user and wait for explicit approval.",
  review:
    "Produce drafts only. A human reviews every output before anything ships. Do not auto-execute tasks.",
};

const PERMISSIONS_BLOCKS: Record<string, string> = {
  strict:
    "Never modify sharing or ACL settings. If a task requires a permission change, surface the request and wait for a human to perform it.",
  domain:
    "Domain-only sharing is acceptable. Do not grant access outside the primary Google Workspace domain.",
  flexible:
    "Permission changes are allowed, but every action must be logged in the team's shared audit document with a timestamp and reason.",
};

const CONFIDENTIALITY_BLOCKS: Record<string, string> = {
  strict:
    "Redact names and identifying details by default. Use role descriptors (\"a senior engineer\", \"a new hire\") unless the user explicitly authorizes naming an individual.",
  standard:
    "Team-level context is acceptable. Avoid referencing individual employees by name in group summaries unless the context warrants it.",
  open:
    "Internal-only context may reference individuals and teams by name. Do not apply proactive redaction unless the user asks.",
};

function labelFor(slot: Slot, id: unknown): string {
  if (typeof id !== "string") return String(id ?? "");
  return slot.options?.find((o) => o.id === id)?.label ?? id;
}

function listOf(items: string[]): string {
  if (items.length === 0) return "(none provided)";
  return items.map((i) => `- ${i}`).join("\n");
}

function buildContext(
  schema: SkillSchema,
  profile: Record<string, unknown>,
): Record<string, string> {
  const ctx: Record<string, string> = {};

  for (const slot of schema.slots) {
    const raw = profile[slot.key];

    if (slot.kind === "text") {
      ctx[slot.key] = typeof raw === "string" ? raw : "(not provided)";
      ctx[`${slot.key}Label`] = ctx[slot.key];
      continue;
    }

    if (slot.kind === "choice") {
      const label = labelFor(slot, raw);
      ctx[slot.key] = typeof raw === "string" ? raw : "";
      ctx[`${slot.key}Label`] = label;
      continue;
    }

    if (slot.kind === "multi") {
      const ids = Array.isArray(raw) ? raw.filter((v): v is string => typeof v === "string") : [];
      const labels = ids.map((id) => labelFor(slot, id));
      ctx[slot.key] = ids.join(",");
      ctx[`${slot.key}Labels`] = labels.join(", ");
      ctx[`${slot.key}List`] = listOf(labels);
    }
  }

  const approval = typeof profile.approval === "string" ? profile.approval : "confirm";
  ctx.approvalBlock = APPROVAL_BLOCKS[approval] ?? APPROVAL_BLOCKS.confirm;

  if (typeof profile.permissions === "string") {
    ctx.permissionsBlock =
      PERMISSIONS_BLOCKS[profile.permissions] ?? PERMISSIONS_BLOCKS.strict;
  }
  if (typeof profile.confidentiality === "string") {
    ctx.confidentialityBlock =
      CONFIDENTIALITY_BLOCKS[profile.confidentiality] ?? CONFIDENTIALITY_BLOCKS.standard;
  }

  if (typeof profile.stages === "string") {
    const stages = profile.stages
      .split(/[,\n]/)
      .map((s) => s.trim())
      .filter(Boolean);
    ctx.stagesList = listOf(stages);
  }

  return ctx;
}

function render(template: string, ctx: Record<string, string>): string {
  return template.replace(/\{\{\s*(\w+)\s*\}\}/g, (match, key: string) =>
    Object.prototype.hasOwnProperty.call(ctx, key) ? ctx[key] : match,
  );
}

export function buildSkill(
  skillId: string,
  profile: Record<string, unknown>,
): BuildResult | null {
  const schema = getSchema(skillId);
  const template = getTemplate(skillId);
  if (!schema || !template) return null;

  const ctx = buildContext(schema, profile);
  const description = render(template.skillDescription, ctx);
  const body = render(template.skillBody, ctx);

  const skillMd = `---
name: ${template.folderName}
description: ${description.replace(/\n/g, " ").trim()}
---

${body}`;

  const readme = `# ${template.skillDisplayName}

This skill was generated by Skillforge for your team. It's a standalone Agent Skill
folder that can be dropped into any compatible agent runtime (for example,
Claude Code's \`~/.claude/skills/\` directory or the Claude Agent SDK).

## Install

1. Unzip this folder to your agent's skills directory.
   For Claude Code: \`~/.claude/skills/${template.folderName}\`
2. Restart your agent (or reload skills).
3. The skill will be loaded automatically when relevant to the task.

## Files

- \`SKILL.md\` — the skill definition consumed by the agent.
- \`config.json\` — the raw configuration captured from your interview, kept
  alongside for traceability. Safe to delete if you don't need the audit trail.
- \`README.md\` — this file.

## Regenerating

If your team's setup changes, open a new private room on Skillforge and
re-run the interview. Your new skill folder will supersede this one.
`;

  const config = JSON.stringify(
    {
      skillId,
      generatedAt: new Date().toISOString(),
      profile,
    },
    null,
    2,
  );

  return {
    folderName: template.folderName,
    files: [
      { path: `${template.folderName}/SKILL.md`, content: skillMd },
      { path: `${template.folderName}/README.md`, content: readme },
      { path: `${template.folderName}/config.json`, content: config },
    ],
  };
}
